when:
  - event: pull_request
  - event: push
    branch: main

steps:
  check-fmt:
    image: nixos/nix:2.35.1
    environment:
      NIX_CONFIG: |
        experimental-features = nix-command flakes
        accept-flake-config = true
    commands:
      - nix fmt -- --ci

  build:
    image: nixos/nix:2.35.1
    environment:
      NIX_CONFIG: |
        experimental-features = nix-command flakes
        accept-flake-config = true
    commands:
      - nix build --print-build-logs
